services:
  api:
    build:
      context: ..
      dockerfile: trucode_data_management_tools/Dockerfile
      args:
        - PORT=:443
        - GIN_MODE=release
    ports:
      - 443:443
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME